name: Weekly Ethereum Newsletter

on:
  schedule:
  # Triggers at 15:00 UTC every Friday (8:00 AM PDT)
    - cron: '0 15 * * 5'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_context:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Python and requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build Prompt Context (last 7 days)
        run: python scripts/build_prompt_context.py
        
      - name: Print context
        run: cat scripts/prompt_context.md

      - name: Upload context file for other jobs
        uses: actions/upload-artifact@v4
        with:
          name: context-data
          path: scripts/prompt_context.md

  generate_part_1:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: build_context
    uses: ./.github/workflows/run-single-section.yml
    with:
      part_number: 1
    secrets: inherit # This correctly passes your LLM_API_KEY

  generate_part_2:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: generate_part_1 
    uses: ./.github/workflows/run-single-section.yml
    with:
      part_number: 2
    secrets: inherit

  generate_part_3:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: generate_part_2
    uses: ./.github/workflows/run-single-section.yml
    with:
      part_number: 3
      context_needed: true
    secrets: inherit

  combine_and_send:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: generate_part_3
    runs-on: ubuntu-latest
    steps:
      - name: Download all partial newsletter files
        uses: actions/download-artifact@v4
        with:
          path: final_parts

      - name: Combine and Stage Newsletter
        id: combine
        run: |
          mkdir -p final_newsletter_output
      
          TIMESTAMP_FILE=$(date -u +"%Y%m%d")
          TIMESTAMP_PRETTY=$(date -u +"%B %d, %Y")
          SUBJECT="Week in Ethereum News - $TIMESTAMP_PRETTY"
          TITLE_DATE=$(date -u +"%Y-%m-%d")
      
          SITE_BASE_URL="${{ vars.SITE_BASE_URL }}"
          if [ -z "$SITE_BASE_URL" ]; then SITE_BASE_URL="https://wie.ercref.org"; fi
      
          PERMALINK="$SITE_BASE_URL/blog/${TIMESTAMP_FILE}/"
      
          FINAL_PATH_IN_REPO="content/blog/${TIMESTAMP_FILE}.md"
          TEMP_FILE="final_newsletter_output/${TIMESTAMP_FILE}.md"
      
          cat <<EOF > "$TEMP_FILE"
          ---
          title: "New Week in Ethereum ${TITLE_DATE}"
          permalink: "/blog/${TIMESTAMP_FILE}/"
          ---
          
          ## Week in Ethereum News
          ### ${TIMESTAMP_PRETTY}
          
          [See this newsletter in your browser](${PERMALINK})
          
          EOF
      
          for part_file in $(find final_parts/ -name "part_*_output.md" | sort); do
            cat "$part_file" >> "$TEMP_FILE"
            echo -e "\n\n" >> "$TEMP_FILE"
          done
      
          echo "--- Final Newsletter created temporarily ---"
          cat "$TEMP_FILE"
      
          echo "subject=$SUBJECT" >> "$GITHUB_OUTPUT"
          echo "final_path=$FINAL_PATH_IN_REPO" >> "$GITHUB_OUTPUT"
          echo "temp_file_path=$TEMP_FILE" >> "$GITHUB_OUTPUT"
          echo "permalink=$PERMALINK" >> "$GITHUB_OUTPUT"
            
      - name: Check out website repository
        uses: actions/checkout@v4
        with:
          repository: 'ercref/new-wie-site' 
          token: ${{ secrets.GH_PAT }}
          path: 'website'

      - name: Move newsletter to website repo
        run: |
          mkdir -p website/content/blog
          # This now uses the correct variable for the destination path
          mv final_newsletter_output/*.md website/${{ steps.combine.outputs.final_path }}
          
      - name: Commit and Push to Website Repo 🚀
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./website
          commit_message: "docs: Publish newsletter for ${{ steps.combine.outputs.subject }} [skip ci]"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
