name: Week-in-Ethereum

on:
  schedule:
    # Run at 5:00am Pacific Time (12:00 UTC) every Monday
    - cron: '0 12 * * 1'
  push: # for development testing
    branches:
      - main
    paths:
      - '.github/workflows/week-in-ethereum.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  summarize-blogs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate timestamp
        id: generate-timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
      - name: Generate Week-in-Ethereum via OpenHands
        uses: xinbenlv/openhands-action@v1.0.1-rc3
        with:
          prompt: >-
            Please help summarize the latest news in last week in Ethereum
            development that looks like each episode of
            https://weekinethereum.substack.com/archive. Remember to preserve
            all links and references in the output.          
            Save the output to file: week_in_ethereum_${{ env.TIMESTAMP }}.md
            Use date range: past 7 days
          llm_api_key: ${{ secrets.LLM_API_KEY }}
      
      - name: Upload Summary Report
        uses: actions/upload-artifact@v4
        with:
          name: week-in-ethereum
          path: week_in_ethereum_*.md
          retention-days: 7
          if-no-files-found: warn

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send Report to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          python send_to_slack.py \
            --input_file "week_in_ethereum_${{ env.TIMESTAMP }}.md" \
            --channel "#random" \
            --use_thread 