name: Weekly Ethereum Newsletter

on:
  schedule:
    # Every Monday 12:00 UTC
    - cron: '0 15 * * 5'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: generate-timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Install Python and requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Prompt Context (last 7 days)
        run: python scripts/build_prompt_context.py

      - name: Print context
        run: cat scripts/prompt_context.md

      - name: Generate Ethereum Newsletter Part 1 via OpenHands
        uses: xinbenlv/openhands-action@v1.0.1-rc3
        with:
          prompt: >- 
            Read prompts/prompt_1.md from the root of the repository and use 
            it to generate a newsletter.
            Use date range: past 7 days
            Save the result to: newsletter1_${{ env.TIMESTAMP }}.md

          llm_api_key: ${{ secrets.LLM_API_KEY }}
          
      - name: Generate Ethereum Newsletter Part 2 via OpenHands
        uses: xinbenlv/openhands-action@v1.0.1-rc3
        with:
          prompt: >- 
            Read prompts/prompt_2.md from the root of the repository and use 
            it to generate a newsletter.
            Use date range: past 7 days
            Save the result to: newsletter2_${{ env.TIMESTAMP }}.md

          llm_api_key: ${{ secrets.LLM_API_KEY }}

      - name: Generate Ethereum Newsletter Part 3 via OpenHands
        uses: xinbenlv/openhands-action@v1.0.1-rc3
        with:
          prompt: >- 
            Read prompts/prompt_3.md from the root of the repository and use 
            it to generate a newsletter.
            Your structured context data is located at 'scripts/prompt_context.md' in your workspace.
            Please read this file to obtain the structured context data.
            Use date range: past 7 days
            Save the result to: newsletter3_${{ env.TIMESTAMP }}.md
  
          llm_api_key: ${{ secrets.LLM_API_KEY }}

      - name: Combine Newsletter Sections
        run: |
          sudo chown -R $(id -u):$(id -g) ${{ github.workspace }}
          
          FINAL_FILE="${{ github.workspace }}/final_newsletter.md"
          PART1_FILE="${{ github.workspace }}/newsletter1_${{ env.TIMESTAMP }}.md"
          PART2_FILE="${{ github.workspace }}/newsletter2_${{ env.TIMESTAMP }}.md"
          PART3_FILE="${{ github.workspace }}/newsletter3_${{ env.TIMESTAMP }}.md"
          
          TIMESTAMP_HEADER=$(date -u +"%B %d, %Y")

          echo "## Week in Ethereum News" > "$FINAL_FILE"
          echo "### $TIMESTAMP_HEADER" >> "$FINAL_FILE"
          echo "" >> "$FINAL_FILE"

          if [ -f "$PART1_FILE" ]; then
            echo "Appending Part 1..."
            cat "$PART1_FILE" >> "$FINAL_FILE"
            echo "" >> "$FINAL_FILE"
          fi
          if [ -f "$PART2_FILE" ]; then
            echo "Appending Part 2..."
            cat "$PART2_FILE" >> "$FINAL_FILE"
            echo "" >> "$FINAL_FILE"
          fi
          if [ -f "$PART3_FILE" ]; then
            echo "Appending Part 3..."
            cat "$PART3_FILE" >> "$FINAL_FILE"
            echo "" >> "$FINAL_FILE"
          fi
          
          echo "--- Final Combined Newsletter ---"
          cat "$FINAL_FILE"
          echo "---------------------------------"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install resend and markdown2
        run: pip install resend markdown2

      - name: Send Newsletter via Resend
        run: |
          if [ $(wc -l < "${{ github.workspace }}/final_newsletter.md") -lt 5 ]; then
            echo "::error::Final newsletter file is empty because generation steps failed after all retries. Halting."
            exit 1
          fi
          pip install markdown2 resend
          python scripts/send_newsletter.py "${{ github.workspace }}/final_newsletter.md"
        env:
          NEWSLETTER_RECIPIENT: ${{ secrets.NEWSLETTER_RECIPIENT }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
