name: Weekly Ethereum Newsletter

on:
  schedule:
    # Every Monday 12:00 UTC
    - cron: '0 15 * * 5'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: generate-timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build Prompt Context (last 7 days)
        run: python scripts/build_prompt_context.py

      - name: Print context contents
        run: cat scripts/prompt_context.md

      - name: Generate Ethereum Newsletter via OpenHands
        uses: xinbenlv/openhands-action@v1.0.1-rc3
        with:
          prompt: >- 
            Read scripts/prompt.md from the root of the repository and use 
            it to generate a newsletter.
            Your structured context data is located at 'scripts/prompt_context.md' in your workspace.
            Please read this file to obtain the structured context data.
            Use date range: past 7 days
            Save the result to: newsletter_${{ env.TIMESTAMP }}.md
  
          llm_api_key: ${{ secrets.LLM_API_KEY }}
      
      - name: Debug Workspace Contents Before Artifact Upload
        run: |
          echo "Current working directory: $(pwd)"
          echo "--- Listing GITHUB_WORKSPACE (${{ github.workspace }}) root contents (ls -la): ---"
          ls -la ${{ github.workspace }}
          echo "--- Recursively listing GITHUB_WORKSPACE contents (ls -laR) - showing all files in all subdirectories: ---"
          ls -laR ${{ github.workspace }}
          echo "--- Trying to find 'newsletter_*.md' files in GITHUB_WORKSPACE specifically: ---"
          find ${{ github.workspace }} -name "newsletter_*.md" -ls
          echo "--- Specifically checking for the exact file the AI claimed to save: ---"
          ls -la ${{ github.workspace }}/newsletter_${{ env.TIMESTAMP }}.md || echo "Exact file ${{ github.workspace }}/newsletter_${{ env.TIMESTAMP }}.md not found by ls"
          echo "--- End of Debug Workspace Contents ---"

      - name: Upload Summary Report
        uses: actions/upload-artifact@v4
        with:
          name: weekly-ethereum-newsletter
          path: newsletter_*.md
          retention-days: 14
          if-no-files-found: warn

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies round 2
        run: pip install resend markdown2

      - name: Send Ethereum Newsletter via Resend
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          NEWSLETTER_RECIPIENT: ${{ secrets.NEWSLETTER_RECIPIENT }}
          TIMESTAMP: ${{ env.TIMESTAMP }}
        run: |
          # Find the latest generated newsletter file
          ls -la  # 🔍 Add this to log the current directory and all files

          FILE=$(ls newsletter_*.md 2>/dev/null | tail -n 1)

          if [ -z "$FILE" ]; then
            echo "❌ No newsletter file found in current directory."
            exit 1
          fi

          echo "✅ Using $FILE"
          python scripts/send_newsletter.py "$FILE"
